var dir_5050f3de292bd66075be80c4b119f1df =
[
    [ "alarm.h", "alarm_8h.html", "alarm_8h" ],
    [ "atomic64.h", "atomic64_8h.html", "atomic64_8h" ],
    [ "baseheap.h", "baseheap_8h.html", "baseheap_8h" ],
    [ "cache.h", "cache_8h.html", "cache_8h" ],
    [ "condition.h", "condition_8h.html", "condition_8h" ],
    [ "core.h", "core_8h.html", "core_8h" ],
    [ "debug.h", "debug_8h.html", "debug_8h" ],
    [ "dynload.h", "dynload_8h.html", "dynload_8h" ],
    [ "event.h", "coreinit_2event_8h.html", "coreinit_2event_8h" ],
    [ "exception.h", "exception_8h.html", "exception_8h" ],
    [ "exit.h", "exit_8h.html", "exit_8h" ],
    [ "expandedheap.h", "expandedheap_8h.html", "expandedheap_8h" ],
    [ "fastcondition.h", "fastcondition_8h.html", "fastcondition_8h" ],
    [ "fastmutex.h", "fastmutex_8h.html", "fastmutex_8h" ],
    [ "frameheap.h", "frameheap_8h.html", "frameheap_8h" ],
    [ "memlist.h", "memlist_8h.html", "memlist_8h" ],
    [ "messagequeue.h", "messagequeue_8h.html", "messagequeue_8h" ],
    [ "mutex.h", "mutex_8h.html", "mutex_8h" ],
    [ "rendezvous.h", "rendezvous_8h.html", "rendezvous_8h" ],
    [ "semaphore.h", "semaphore_8h.html", "semaphore_8h" ],
    [ "spinlock.h", "spinlock_8h.html", "spinlock_8h" ],
    [ "taskqueue.h", "taskqueue_8h.html", "taskqueue_8h" ],
    [ "thread.h", "thread_8h.html", "thread_8h" ],
    [ "threadqueue.h", "threadqueue_8h.html", "threadqueue_8h" ],
    [ "time.h", "time_8h.html", "time_8h" ],
    [ "unitheap.h", "unitheap_8h.html", "unitheap_8h" ]
];