var group__coreinit =
[
    [ "Alarms", "group__coreinit__alarms.html", "group__coreinit__alarms" ],
    [ "Atomic 64 bit", "group__coreinit__atomic64.html", "group__coreinit__atomic64" ],
    [ "Base Heap", "group__coreinit__baseheap.html", "group__coreinit__baseheap" ],
    [ "Cache", "group__coreinit__cache.html", "group__coreinit__cache" ],
    [ "Condition Variable", "group__coreinit__cond.html", "group__coreinit__cond" ],
    [ "Core Identification", "group__coreinit__core.html", "group__coreinit__core" ],
    [ "Debug", "group__coreinit__debug.html", "group__coreinit__debug" ],
    [ "Dynamic Loading", "group__coreinit__dynload.html", "group__coreinit__dynload" ],
    [ "Event Object", "group__coreinit__event.html", "group__coreinit__event" ],
    [ "Exception Handling", "group__coreinit__exception.html", "group__coreinit__exception" ],
    [ "Exit", "group__coreinit__exit.html", "group__coreinit__exit" ],
    [ "Expanded Heap", "group__coreinit__expheap.html", "group__coreinit__expheap" ],
    [ "Fast Condition Variable", "group__coreinit__fastcond.html", "group__coreinit__fastcond" ],
    [ "Fast Mutex", "group__coreinit__fastmutex.html", "group__coreinit__fastmutex" ],
    [ "Frame Heap", "group__coreinit__frameheap.html", "group__coreinit__frameheap" ],
    [ "Memory List", "group__coreinit__memlist.html", "group__coreinit__memlist" ],
    [ "Message Queue", "group__coreinit__msgq.html", "group__coreinit__msgq" ],
    [ "Mutex", "group__coreinit__mutex.html", "group__coreinit__mutex" ],
    [ "Rendezvous", "group__coreinit__rendezvous.html", "group__coreinit__rendezvous" ],
    [ "Semaphore", "group__coreinit__semaphore.html", "group__coreinit__semaphore" ],
    [ "Spinlock", "group__coreinit__spinlock.html", "group__coreinit__spinlock" ],
    [ "Task Queue", "group__coreinit__taskq.html", "group__coreinit__taskq" ],
    [ "Thread", "group__coreinit__thread.html", "group__coreinit__thread" ],
    [ "Thread Queue", "group__coreinit__threadq.html", "group__coreinit__threadq" ],
    [ "Time", "group__coreinit__time.html", "group__coreinit__time" ],
    [ "Unit Heap", "group__coreinit__unitheap.html", "group__coreinit__unitheap" ]
];