var searchData=
[
  ['acpmetaxml_6186',['ACPMetaXml',['../group__nn__acp__title.html#structACPMetaXml',1,'']]],
  ['addrinfo_6187',['addrinfo',['../netdb_8h.html#structaddrinfo',1,'']]],
  ['admininfo_6188',['AdminInfo',['../namespacenn_1_1nfp.html#structnn_1_1nfp_1_1AdminInfo',1,'nn::nfp']]],
  ['amiibosettingsargs_6189',['AmiiboSettingsArgs',['../namespacenn_1_1nfp.html#structnn_1_1nfp_1_1AmiiboSettingsArgs',1,'nn::nfp']]],
  ['amiibosettingsargsin_6190',['AmiiboSettingsArgsIn',['../namespacenn_1_1nfp.html#structnn_1_1nfp_1_1AmiiboSettingsArgsIn',1,'nn::nfp']]],
  ['amiibosettingsresult_6191',['AmiiboSettingsResult',['../namespacenn_1_1nfp.html#structnn_1_1nfp_1_1AmiiboSettingsResult',1,'nn::nfp']]],
  ['appeararg_6192',['AppearArg',['../namespacenn_1_1erreula.html#structnn_1_1erreula_1_1AppearArg',1,'AppearArg'],['../namespacenn_1_1swkbd.html#structnn_1_1swkbd_1_1AppearArg',1,'AppearArg']]],
  ['applicationareacreateinfo_6193',['ApplicationAreaCreateInfo',['../namespacenn_1_1nfp.html#structnn_1_1nfp_1_1ApplicationAreaCreateInfo',1,'nn::nfp']]],
  ['axinitparams_6194',['AXInitParams',['../group__sndcore2__core.html#structAXInitParams',1,'']]],
  ['axprofile_6195',['AXProfile',['../group__sndcore2__core.html#structAXProfile',1,'']]],
  ['axtransitionaudiobuffer_6196',['AXTransitionAudioBuffer',['../group__sndcore2__core.html#structAXTransitionAudioBuffer',1,'']]],
  ['axvoice_6197',['AXVoice',['../group__sndcore2__voice.html#structAXVoice',1,'']]],
  ['axvoiceadpcm_6198',['AXVoiceAdpcm',['../group__sndcore2__voice.html#structAXVoiceAdpcm',1,'']]],
  ['axvoiceadpcmloopdata_6199',['AXVoiceAdpcmLoopData',['../group__sndcore2__voice.html#structAXVoiceAdpcmLoopData',1,'']]],
  ['axvoicedevicebusmixdata_6200',['AXVoiceDeviceBusMixData',['../group__sndcore2__voice.html#structAXVoiceDeviceBusMixData',1,'']]],
  ['axvoicedevicemixdata_6201',['AXVoiceDeviceMixData',['../group__sndcore2__voice.html#structAXVoiceDeviceMixData',1,'']]],
  ['axvoicelink_6202',['AXVoiceLink',['../group__sndcore2__voice.html#structAXVoiceLink',1,'']]],
  ['axvoiceoffsets_6203',['AXVoiceOffsets',['../group__sndcore2__voice.html#structAXVoiceOffsets',1,'']]],
  ['axvoicesrc_6204',['AXVoiceSrc',['../group__sndcore2__voice.html#structAXVoiceSrc',1,'']]],
  ['axvoicevedata_6205',['AXVoiceVeData',['../group__sndcore2__voice.html#structAXVoiceVeData',1,'']]]
];
