var searchData=
[
  ['scrambledlocalfriendcode_7900',['ScrambledLocalFriendCode',['../namespacenn_1_1uds_1_1Cafe.html#structnn_1_1uds_1_1Cafe_1_1ScrambledLocalFriendCode',1,'nn::uds::Cafe']]],
  ['serializerfromptr_7901',['SerializerFromPtr',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['serializerfromptr_3c_20nn_3a_3asl_3a_3akillernotification_20_3e_7902',['SerializerFromPtr&lt; nn::sl::KillerNotification &gt;',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['serializerfromptr_3c_20nn_3a_3asl_3a_3atitleinfo_20_3e_7903',['SerializerFromPtr&lt; nn::sl::TitleInfo &gt;',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['serializerfromptr_3c_20ostime_20_3e_7904',['SerializerFromPtr&lt; OSTime &gt;',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['servent_7905',['servent',['../netdb_8h.html#structservent',1,'']]],
  ['setting_7906',['Setting',['../namespacenn_1_1sl.html#structnn_1_1sl_1_1Setting',1,'nn::sl']]],
  ['setting_2ecaffeine_7907',['Setting.caffeine',['../namespacenn_1_1sl.html#structnn_1_1sl_1_1Setting_8caffeine',1,'nn::sl']]],
  ['settingaccessorfromptr_7908',['SettingAccessorFromPtr',['../classnn_1_1sl_1_1details_1_1SettingAccessorFromPtr.html',1,'nn::sl::details']]],
  ['smdctrltable_7909',['SmdCtrlTable',['../group__coreinit__smd.html#structSmdCtrlTable',1,'']]],
  ['smdelement_7910',['SmdElement',['../group__coreinit__smd.html#structSmdElement',1,'']]],
  ['smdelement_2e_5f_5funnamed9_5f_5f_7911',['SmdElement.__unnamed9__',['../group__coreinit__smd.html#unionSmdElement_8____unnamed9____',1,'']]],
  ['smdinterface_7912',['SmdInterface',['../group__coreinit__smd.html#structSmdInterface',1,'']]],
  ['smdppc_7913',['SmdPpc',['../group__coreinit__smd.html#structSmdPpc',1,'']]],
  ['smdppcctrltablevectors_7914',['SmdPpcCtrlTableVectors',['../group__coreinit__smd.html#structSmdPpcCtrlTableVectors',1,'']]],
  ['smdreceivedata_7915',['SmdReceiveData',['../group__coreinit__smd.html#structSmdReceiveData',1,'']]],
  ['smdreceivedata_2e_5f_5funnamed11_5f_5f_7916',['SmdReceiveData.__unnamed11__',['../group__coreinit__smd.html#unionSmdReceiveData_8____unnamed11____',1,'']]],
  ['smdsimplebufpool_7917',['SmdSimpleBufPool',['../group__coreinit__smd.html#structSmdSimpleBufPool',1,'']]],
  ['smdvector_7918',['SmdVector',['../group__coreinit__smd.html#structSmdVector',1,'']]],
  ['smdvectorspec_7919',['SmdVectorSpec',['../group__coreinit__smd.html#structSmdVectorSpec',1,'']]],
  ['sockaddr_7920',['sockaddr',['../sys_2socket_8h.html#structsockaddr',1,'']]],
  ['sockaddr_5fin_7921',['sockaddr_in',['../in_8h.html#structsockaddr__in',1,'']]],
  ['sockaddr_5fstorage_7922',['sockaddr_storage',['../sys_2socket_8h.html#structsockaddr__storage',1,'']]],
  ['storageinfo_7923',['StorageInfo',['../namespacenn_1_1spm.html#structnn_1_1spm_1_1StorageInfo',1,'nn::spm']]],
  ['storagelistitem_7924',['StorageListItem',['../namespacenn_1_1spm.html#structnn_1_1spm_1_1StorageListItem',1,'nn::spm']]],
  ['sysappbrowserargs_7925',['SysAppBrowserArgs',['../group__sysapp__switch.html#structSysAppBrowserArgs',1,'']]],
  ['sysappbrowserargswithcallback_7926',['SysAppBrowserArgsWithCallback',['../group__sysapp__switch.html#structSysAppBrowserArgsWithCallback',1,'']]],
  ['sysappemanualargs_7927',['SysAppEManualArgs',['../group__sysapp__switch.html#structSysAppEManualArgs',1,'']]],
  ['sysappeshopargs_7928',['SysAppEShopArgs',['../group__sysapp__switch.html#structSysAppEShopArgs',1,'']]],
  ['sysappmiimakerargs_7929',['SysAppMiiMakerArgs',['../group__sysapp__launch.html#structSysAppMiiMakerArgs',1,'']]],
  ['sysappnotificationargs_7930',['SysAppNotificationArgs',['../group__sysapp__launch.html#structSysAppNotificationArgs',1,'']]],
  ['sysappparentalargs_7931',['SysAppParentalArgs',['../group__sysapp__launch.html#structSysAppParentalArgs',1,'']]],
  ['sysappsettingsargs_7932',['SysAppSettingsArgs',['../group__sysapp__launch.html#structSysAppSettingsArgs',1,'']]],
  ['sysargdatablock_7933',['SYSArgDataBlock',['../group__sysapp__args.html#structSYSArgDataBlock',1,'']]],
  ['sysargdatablock_2e_5f_5funnamed47_5f_5f_7934',['SYSArgDataBlock.__unnamed47__',['../group__sysapp__args.html#unionSYSArgDataBlock_8____unnamed47____',1,'']]],
  ['sysargdatablock_2e_5f_5funnamed47_5f_5f_2edata_7935',['SYSArgDataBlock.__unnamed47__.data',['../group__sysapp__args.html#structSYSArgDataBlock_8____unnamed47_____8data',1,'']]],
  ['sysargdatablock_2e_5f_5funnamed47_5f_5f_2estring_7936',['SYSArgDataBlock.__unnamed47__.string',['../group__sysapp__args.html#structSYSArgDataBlock_8____unnamed47_____8string',1,'']]],
  ['syscallerinfo_7937',['SYSCallerInfo',['../group__sysapp__args.html#structSYSCallerInfo',1,'']]],
  ['sysdeserializearg_7938',['SYSDeserializeArg',['../group__sysapp__args.html#structSYSDeserializeArg',1,'']]],
  ['sysstandardargs_7939',['SYSStandardArgs',['../group__sysapp__args.html#structSYSStandardArgs',1,'']]],
  ['sysstandardargsin_7940',['SYSStandardArgsIn',['../group__sysapp__args.html#structSYSStandardArgsIn',1,'']]],
  ['sysstandardargsout_7941',['SYSStandardArgsOut',['../group__sysapp__args.html#structSYSStandardArgsOut',1,'']]]
];
