var searchData=
[
  ['scrambledlocalfriendcode_0',['ScrambledLocalFriendCode',['../namespacenn_1_1uds_1_1Cafe.html#structnn_1_1uds_1_1Cafe_1_1ScrambledLocalFriendCode',1,'nn::uds::Cafe']]],
  ['serializerfromptr_1',['SerializerFromPtr',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['serializerfromptr_3c_20nn_3a_3asl_3a_3akillernotification_20_3e_2',['SerializerFromPtr&lt; nn::sl::KillerNotification &gt;',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['serializerfromptr_3c_20nn_3a_3asl_3a_3atitleinfo_20_3e_3',['SerializerFromPtr&lt; nn::sl::TitleInfo &gt;',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['serializerfromptr_3c_20ostime_20_3e_4',['SerializerFromPtr&lt; OSTime &gt;',['../classnn_1_1sl_1_1details_1_1SerializerFromPtr.html',1,'nn::sl::details']]],
  ['servent_5',['servent',['../netdb_8h.html#structservent',1,'']]],
  ['server_6',['Server',['../classnn_1_1dlp_1_1Cafe_1_1Server.html',1,'nn::dlp::Cafe']]],
  ['serverprivate_7',['ServerPrivate',['../classnn_1_1dlp_1_1Cafe_1_1ServerPrivate.html',1,'nn::dlp::Cafe']]],
  ['setting_8',['Setting',['../namespacenn_1_1sl.html#structnn_1_1sl_1_1Setting',1,'nn::sl']]],
  ['setting_2ecaffeine_9',['Setting.caffeine',['../namespacenn_1_1sl.html#structnn_1_1sl_1_1Setting_8caffeine',1,'nn::sl']]],
  ['settingaccessorfromptr_10',['SettingAccessorFromPtr',['../classnn_1_1sl_1_1details_1_1SettingAccessorFromPtr.html',1,'nn::sl::details']]],
  ['smdctrltable_11',['SmdCtrlTable',['../group__coreinit__smd.html#structSmdCtrlTable',1,'']]],
  ['smdelement_12',['SmdElement',['../group__coreinit__smd.html#structSmdElement',1,'']]],
  ['smdelement_2e_5f_5funnamed13_5f_5f_13',['SmdElement.__unnamed13__',['../group__coreinit__smd.html#unionSmdElement_8____unnamed13____',1,'']]],
  ['smdinterface_14',['SmdInterface',['../group__coreinit__smd.html#structSmdInterface',1,'']]],
  ['smdppc_15',['SmdPpc',['../group__coreinit__smd.html#structSmdPpc',1,'']]],
  ['smdppcctrltablevectors_16',['SmdPpcCtrlTableVectors',['../group__coreinit__smd.html#structSmdPpcCtrlTableVectors',1,'']]],
  ['smdreceivedata_17',['SmdReceiveData',['../group__coreinit__smd.html#structSmdReceiveData',1,'']]],
  ['smdreceivedata_2e_5f_5funnamed15_5f_5f_18',['SmdReceiveData.__unnamed15__',['../group__coreinit__smd.html#unionSmdReceiveData_8____unnamed15____',1,'']]],
  ['smdsimplebufpool_19',['SmdSimpleBufPool',['../group__coreinit__smd.html#structSmdSimpleBufPool',1,'']]],
  ['smdvector_20',['SmdVector',['../group__coreinit__smd.html#structSmdVector',1,'']]],
  ['smdvectorspec_21',['SmdVectorSpec',['../group__coreinit__smd.html#structSmdVectorSpec',1,'']]],
  ['sockaddr_22',['sockaddr',['../sys_2socket_8h.html#structsockaddr',1,'']]],
  ['sockaddr_5fin_23',['sockaddr_in',['../in_8h.html#structsockaddr__in',1,'']]],
  ['sockaddr_5fstorage_24',['sockaddr_storage',['../sys_2socket_8h.html#structsockaddr__storage',1,'']]],
  ['storageinfo_25',['StorageInfo',['../namespacenn_1_1spm.html#structnn_1_1spm_1_1StorageInfo',1,'nn::spm']]],
  ['storagelistitem_26',['StorageListItem',['../namespacenn_1_1spm.html#structnn_1_1spm_1_1StorageListItem',1,'nn::spm']]],
  ['sysappbrowserargs_27',['SysAppBrowserArgs',['../group__sysapp__switch.html#structSysAppBrowserArgs',1,'']]],
  ['sysappbrowserargswithcallback_28',['SysAppBrowserArgsWithCallback',['../group__sysapp__switch.html#structSysAppBrowserArgsWithCallback',1,'']]],
  ['sysappemanualargs_29',['SysAppEManualArgs',['../group__sysapp__switch.html#structSysAppEManualArgs',1,'']]],
  ['sysappeshopargs_30',['SysAppEShopArgs',['../group__sysapp__switch.html#structSysAppEShopArgs',1,'']]],
  ['sysappmiimakerargs_31',['SysAppMiiMakerArgs',['../group__sysapp__launch.html#structSysAppMiiMakerArgs',1,'']]],
  ['sysappnotificationargs_32',['SysAppNotificationArgs',['../group__sysapp__launch.html#structSysAppNotificationArgs',1,'']]],
  ['sysappparentalargs_33',['SysAppParentalArgs',['../group__sysapp__launch.html#structSysAppParentalArgs',1,'']]],
  ['sysappsettingsargs_34',['SysAppSettingsArgs',['../group__sysapp__launch.html#structSysAppSettingsArgs',1,'']]],
  ['sysargdatablock_35',['SYSArgDataBlock',['../group__sysapp__args.html#structSYSArgDataBlock',1,'']]],
  ['sysargdatablock_2e_5f_5funnamed61_5f_5f_36',['SYSArgDataBlock.__unnamed61__',['../group__sysapp__args.html#unionSYSArgDataBlock_8____unnamed61____',1,'']]],
  ['sysargdatablock_2e_5f_5funnamed61_5f_5f_2edata_37',['SYSArgDataBlock.__unnamed61__.data',['../group__sysapp__args.html#structSYSArgDataBlock_8____unnamed61_____8data',1,'']]],
  ['sysargdatablock_2e_5f_5funnamed61_5f_5f_2estring_38',['SYSArgDataBlock.__unnamed61__.string',['../group__sysapp__args.html#structSYSArgDataBlock_8____unnamed61_____8string',1,'']]],
  ['syscallerinfo_39',['SYSCallerInfo',['../group__sysapp__args.html#structSYSCallerInfo',1,'']]],
  ['sysdeserializearg_40',['SYSDeserializeArg',['../group__sysapp__args.html#structSYSDeserializeArg',1,'']]],
  ['sysstandardargs_41',['SYSStandardArgs',['../group__sysapp__args.html#structSYSStandardArgs',1,'']]],
  ['sysstandardargsin_42',['SYSStandardArgsIn',['../group__sysapp__args.html#structSYSStandardArgsIn',1,'']]],
  ['sysstandardargsout_43',['SYSStandardArgsOut',['../group__sysapp__args.html#structSYSStandardArgsOut',1,'']]]
];
