var searchData=
[
  ['sampler_0',['Sampler',['../group__gx2__sampler.html',1,'']]],
  ['save_1',['Save',['../group__nn__acp__save.html',1,'']]],
  ['saver_2',['Energy saver',['../group__coreinit__energysaver.html',1,'']]],
  ['scheduler_3',['Scheduler',['../group__coreinit__scheduler.html',1,'']]],
  ['screen_4',['Screen',['../group__coreinit__screen.html',1,'']]],
  ['semaphore_5',['Semaphore',['../group__coreinit__semaphore.html',1,'']]],
  ['shaders_6',['Shaders',['../group__gx2__shader.html',1,'']]],
  ['smd_7',['SMD',['../group__coreinit__smd.html',1,'']]],
  ['sndcore2_8',['sndcore2',['../group__sndcore2.html',1,'']]],
  ['socket_9',['Socket',['../group__nsysnet__socket.html',1,'']]],
  ['software_20keyboard_10',['Software Keyboard',['../group__nn__swkbd__swkbd.html',1,'']]],
  ['spinlock_11',['Spinlock',['../group__coreinit__spinlock.html',1,'']]],
  ['ssl_12',['Nintendo SSL',['../group__nsysnet__nssl.html',1,'']]],
  ['state_13',['state',['../group__gx2__context.html',1,'Context State'],['../group__gx2__state.html',1,'State']]],
  ['stopwatch_14',['stopwatch',['../group__coreinit__stopwatchatomic.html',1,'Atomic Stopwatch'],['../group__coreinit__stopwatch.html',1,'Lock-based Stopwatch']]],
  ['stream_15',['H264 Stream',['../group__h264__stream.html',1,'']]],
  ['surface_16',['surface',['../group__gx2__surface.html',1,'Surface'],['../group__gx2r__surface.html',1,'Surface']]],
  ['swap_17',['Swap',['../group__gx2__swap.html',1,'']]],
  ['switch_18',['SYSAPP Switch',['../group__sysapp__switch.html',1,'']]],
  ['swkbd_19',['swkbd',['../group__swkbd.html',1,'']]],
  ['synchronization_20',['Synchronization',['../group__dmae__sync.html',1,'']]],
  ['sysapp_21',['sysapp',['../group__sysapp.html',1,'']]],
  ['sysapp_20arguments_22',['SYSAPP Arguments',['../group__sysapp__args.html',1,'']]],
  ['sysapp_20launch_23',['SYSAPP Launch',['../group__sysapp__launch.html',1,'']]],
  ['sysapp_20switch_24',['SYSAPP Switch',['../group__sysapp__switch.html',1,'']]],
  ['sysapp_20title_25',['SYSAPP Title',['../group__sysapp__title.html',1,'']]],
  ['system_20config_26',['AVM System Config',['../group__avm__config.html',1,'']]],
  ['system_20info_27',['System Info',['../group__coreinit__systeminfo.html',1,'']]]
];
