var searchData=
[
  ['sampler_12769',['Sampler',['../group__gx2__sampler.html',1,'']]],
  ['save_12770',['Save',['../group__nn__acp__save.html',1,'']]],
  ['scheduler_12771',['Scheduler',['../group__coreinit__scheduler.html',1,'']]],
  ['screen_12772',['Screen',['../group__coreinit__screen.html',1,'']]],
  ['semaphore_12773',['Semaphore',['../group__coreinit__semaphore.html',1,'']]],
  ['shaders_12774',['Shaders',['../group__gx2__shader.html',1,'']]],
  ['smd_12775',['SMD',['../group__coreinit__smd.html',1,'']]],
  ['sndcore2_12776',['sndcore2',['../group__sndcore2.html',1,'']]],
  ['socket_12777',['Socket',['../group__nsysnet__socket.html',1,'']]],
  ['software_20keyboard_12778',['Software Keyboard',['../group__nn__swkbd__swkbd.html',1,'']]],
  ['spinlock_12779',['Spinlock',['../group__coreinit__spinlock.html',1,'']]],
  ['state_12780',['State',['../group__gx2__state.html',1,'']]],
  ['surface_12781',['Surface',['../group__gx2__surface.html',1,'(Global Namespace)'],['../group__gx2r__surface.html',1,'(Global Namespace)']]],
  ['swap_12782',['Swap',['../group__gx2__swap.html',1,'']]],
  ['swkbd_12783',['swkbd',['../group__swkbd.html',1,'']]],
  ['synchronization_12784',['Synchronization',['../group__dmae__sync.html',1,'']]],
  ['sysapp_12785',['sysapp',['../group__sysapp.html',1,'']]],
  ['sysapp_20arguments_12786',['SYSAPP Arguments',['../group__sysapp__args.html',1,'']]],
  ['sysapp_20launch_12787',['SYSAPP Launch',['../group__sysapp__launch.html',1,'']]],
  ['sysapp_20switch_12788',['SYSAPP Switch',['../group__sysapp__switch.html',1,'']]],
  ['sysapp_20title_12789',['SYSAPP Title',['../group__sysapp__title.html',1,'']]],
  ['system_20info_12790',['System Info',['../group__coreinit__systeminfo.html',1,'']]]
];
