// nsysnet/socket.h
EXPORT(socket_lib_init);
EXPORT(socket);
EXPORT(socketclose);
EXPORT(connect);
EXPORT(bind);
EXPORT(listen);
EXPORT(accept);
EXPORT(send);
EXPORT(recv);
EXPORT(sendto);
EXPORT(setsockopt);
EXPORT(recvfrom);
EXPORT(recvfrom_ex);
EXPORT(recvfrom_multi);
EXPORT(sendto_multi);
EXPORT(sendto_multi_ex);
EXPORT(shutdown);
EXPORT(inet_aton);
EXPORT(inet_ntoa);
EXPORT(inet_ntoa_r);
EXPORT(inet_ntop);
EXPORT(inet_pton);
EXPORT(getpeername);
EXPORT(getsockname);
EXPORT(getsockopt);
EXPORT(select);
EXPORT(setsocklibopt);
EXPORT(getsocklibopt);
EXPORT(ntohl);
EXPORT(htonl);
EXPORT(ntohs);
EXPORT(htons);
/*
// Those are not in nsysnet.rpl - why are they linked o.O?
EXPORT(somemopt);
EXPORT(setsocketlasterr);
EXPORT(icmp_create_handle);
EXPORT(icmp_close_handle);
EXPORT(icmp_ping);
EXPORT(icmp_cancel);
EXPORT(icmp_last_code_type);
*/
