name: Documentation

on:
  push:
    tags:
      - '*'

jobs:
  doc:
    name: Deploy documentation
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout the Git repository
      uses: actions/checkout@v2

    - name: Generate Documentation
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake doxygen doxygen-latex graphviz
        cd docs
        sudo cmake .
        doxygen Doxyfile.docs >/dev/null

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.1
      with:
        branch: gh-pages
        folder: docs/html
