name: Documentation

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  doc:
    name: Deploy documentation
    runs-on: ubuntu-20.04

    steps:

    - name: Checkout the Git repository
      uses: actions/checkout@v4

    - name: Fetch tags
      run: |
        git fetch --tags

    - name: Get current tag
      id: vars
      run: echo "tag=`git tag --sort=-version:refname | head -n 1`" >> "$GITHUB_OUTPUT"

    - name: Generate Documentation
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake doxygen doxygen-latex graphviz
        cd docs
        sudo env WUT_VERSION=${{ steps.vars.outputs.tag }} cmake .
        doxygen Doxyfile.docs >/dev/null

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        branch: gh-pages
        folder: docs/html
        single-commit: true
        clean: true
        clean-exclude: CNAME
